# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-26 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.CharField(help_text='Original Url', max_length=2048)),
                ('short_url_key', models.CharField(help_text='Short URL', max_length=20, unique=True)),
            ],
        ),
    ]
