# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-26 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmapping',
            name='short_url_key',
            field=models.CharField(help_text='Short URL', max_length=20, null=True),
        ),
    ]
